"""
Django settings for myshop project.
Generated by 'django-admin startproject' using Django 5.2.
Prepared for deployment on Vercel.
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment Configuration
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development').lower()
SYSTEM_STATE = os.environ.get('SYSTEM_STATE', 'local').lower()  # 'local' or 'cloud'
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-l3=-3j*)d(#jtqqncm77#ez99litg9zj_pg32)jywlm&i%b1m)')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Environment-specific settings
# Read ALLOWED_HOSTS from environment variable if set, otherwise use defaults
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    if ENVIRONMENT == 'production':
        ALLOWED_HOSTS = ['.vercel.app', 'your-production-domain.com']
    elif ENVIRONMENT == 'staging':
        ALLOWED_HOSTS = ['.vercel.app', 'staging.your-domain.com', 'localhost', '127.0.0.1', '.up.railway.app']
    else:  # development/local
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.vercel.app']

if ENVIRONMENT == 'production':
    CORS_ALLOWED_ORIGINS = [
        "https://your-production-frontend.com",
        "https://mwambaliquor.netlify.app",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "https://*.vercel.app",
        "https://your-production-domain.com",
    ]
elif ENVIRONMENT == 'staging':
    CORS_ALLOWED_ORIGINS = [
        "https://staging-frontend.your-domain.com",
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://localhost:3001",
        "http://192.168.10.219:3001",
        "https://*.up.railway.app",  # Railway domains
    ]
    CSRF_TRUSTED_ORIGINS = [
        "https://*.vercel.app",
        "https://staging.your-domain.com",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://*.up.railway.app",  # Railway domains
    ]
else:  # development/local
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://localhost:3001",
        "http://192.168.10.219:3001",
        "https://mwambaliquor.netlify.app",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "https://*.vercel.app",
        "https://*.trycloudflare.com",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://mwambaliquor.netlify.app",
    ]

# Installed apps
INSTALLED_APPS = [
    # Django defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_redis',

    # Local apps
    'sync',
    'users',
    'inventory',
    'sales',
    'payments',
    'customers',
    'repairs',
    'preorders',
    'suppliers',
    'chits',
    'shifts',
    'reports',
    'branches',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'

# ✅ Database Configuration (Environment-based)
if ENVIRONMENT == 'production':
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get('DATABASE_URL', 'postgresql://default:default@localhost:5432/myshop'),
            conn_max_age=600,
            ssl_require=True
        )
    }
elif ENVIRONMENT == 'staging':
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get('STAGING_DATABASE_URL', 'postgresql://default:default@localhost:5432/myshop_staging'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:  # development/local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Sync Configuration (bidirectional for all systems)
SYNC_SETTINGS = {
    'ENABLED': os.environ.get('SYNC_ENABLED', 'True') == 'True',
    'IS_CLOUD': SYSTEM_STATE == 'cloud',
    'CLOUD_URL': os.environ.get('SYNC_CLOUD_URL', ''),
    'API_KEY': os.environ.get('SYNC_API_KEY', ''),
    'BATCH_SIZE': int(os.environ.get('SYNC_BATCH_SIZE', '100')),
    'SYNC_INTERVAL': int(os.environ.get('SYNC_INTERVAL_MINUTES', '5')),
    'CONFLICT_RESOLUTION': os.environ.get('SYNC_CONFLICT_RESOLUTION', 'server_wins'),
    'SYSTEM_STATE': SYSTEM_STATE,
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# ✅ Static & media files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ REST framework & JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# ✅ Cache (using local memory cache)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# ✅ CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://localhost:3001",        # added
    "http://192.168.10.219:3001",   # added
    "https://mwambaliquor.netlify.app",  # added
]

CORS_ALLOW_CREDENTIALS = True

# ✅ CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    "https://*.trycloudflare.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://mwambaliquor.netlify.app",  # added
]

# ✅ Security best practices
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
